### ISSUE TITLE
Error: Cannot find module 'es-to-primitive/es6'

### ISSUE THREAD

**Issue by zeke** [standard/standard#1063]
Seeing this error on Node 8 and 9 when bumping from standard 8.2.0 to 10.0.3

PR: https://github.com/electron/electron-typescript-definitions/pull/91

```
Error: Cannot find module 'es-to-primitive/es6'
Referenced from: /home/travis/build/electron/electron-typescript-definitions/node_modules/standard/eslintrc.json
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/electron/electron-typescript-definitions/node_modules/es-abstract/es2015.js:16:19)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

![image](https://user-images.githubusercontent.com/2289/36113551-0a081c00-0fe2-11e8-8747-4d5943096a25.png)

**Comment by zeke** [comment]
> Want to try upgrading to v11 instead?

That did the trick 👍

**Comment by feross** [comment]
Wohoo! ✨
